### ISSUE TITLE
Receive "bad file descriptor"

### ISSUE THREAD

**Issue by neocite** [joaoricardo000/whatsapp-bot-seed#101]
Hi! I receive the error "bad file descriptor" after 10 minutes the started the server. Can i help me?

```
Traceback (most recent call last):
  File "server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
```

**Comment by ghost** [comment]
#55
