### ISSUE TITLE
ImportError in RouteLayer

### ISSUE THREAD

**Issue by RobValentim** [joaoricardo000/whatsapp-bot-seed#109]
command >> python src/server.py

Traceback (most recent call last):
   File "src/server.py", line 16, in <module>
     from router import RouteLayer
   File "src/router.py", line 13, in <module>
     from views.media import MediaViews
   File "src/views/media.py", line 9, in <module>
     from utils.media_sender import ImageSender, VideoSender, UrlPrintSender, EspeakTtsSender
   File "src/utils/media_sender.py", line 23, in <module>
     import requests
ImportError: No module named requests

maybe needs "requests.py" file

**Comment by ghost** [comment]
Try looking at https://github.com/joaoricardo000/whatsapp-bot-seed#installation
Also, see #100
