### ISSUE TITLE
Joao Preciso muito de sua ajuda '-' pls

### ISSUE THREAD

**Issue by helloitu** [joaoricardo000/whatsapp-bot-seed#15]
tudo deu certo aqui , ja cadastrei o numero e tudo , mas quando vou executar o servidor da esse erro : 

(process:17039): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
dosnut@dosnut-X451CA:~/whatsbot/whatsapp-bot-seed-master/src$ python server.py 
Traceback (most recent call last):
  File "server.py", line 50, in <module>
    server = YowsupEchoStack(config.auth)
  File "server.py", line 29, in __init__
    self.stack.setCredentials(credentials)
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 155, in setCredentials
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 42, in setCredentials
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 37, in __getCredentials
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

 por favor se puder ajudar , agradeço :D

**Comment by joaoricardo000** [comment]
Opa,

Esse erro é por causa que a sua chave está errada.
Provavelmente deve ter algum espaço, ou não tá completa.

Essa é a minha (com alguns caracteres trocados, é claro)

auth = ("5548999997439", "7V5NM9oFn4uTN6BqIUCBEBHg46U=")

Confere de novo a sua chave e garanta que não tem nenhum espaço dentro da string ou que não está faltando o "=" no final.

Abraço

**Comment by helloitu** [comment]
deu certo , vlw
