### ISSUE TITLE
cannot write/read files in mediadirectory

### ISSUE THREAD

**Issue by relative** [joaoricardo000/whatsapp-bot-seed#5]
Traceback (most recent call last):
  File "/home/pi/whatsapp-bot-seed/src/router.py", line 68, in handle_callback
    data = callback(message, match)
  File "/home/pi/whatsapp-bot-seed/src/views/google.py", line 38, in google_search
    self.url_print_sender.send_by_url(jid=message.getFrom(), file_url=page_url)
  File "/home/pi/whatsapp-bot-seed/src/utils/media_sender.py", line 56, in send_by_url
    self._on_error(jid)
  File "/home/pi/whatsapp-bot-seed/src/utils/media_sender.py", line 118, in _on_error
    self.interface_layer.toLower(TextMessageProtocolEntity("{!}", to=jid))
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 169, in handlePlaintextNode
    if not self.store.containsSession(recipient_id, 1):
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 56, in containsSession
    return self.sessionStore.containsSession(recepientId, deviceId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 44, in containsSession
    c.execute(q, (recipientId, deviceId))
InterfaceError: Error binding parameter 0 - probably unsupported type.
_layer.py_      [ERROR][2015-10-23 12:40:10,314] No valid sessionsBad Mac!
_layer.py_      [ERROR][2015-10-23 12:40:10,438] No valid sessionsBad Mac!

**Comment by joaoricardo000** [comment]
Could you add some more information about when this happens?

**Comment by montemarcaldera** [comment]
I'm having the same issue :(

**Comment by montemarcaldera** [comment]
_media_sender.py_       [ERROR][2015-11-07 16:31:01,908] Either specified path does not exist, or yowsup doesn't have permission to read: /root/smartbot/media/ed646a3334ca891fd3467db13137214014469318.jpeg
Traceback (most recent call last):
  File "/root/smartbot/src/utils/media_sender.py", line 53, in send_by_url
    self.send_by_path(jid, file_path, caption)
  File "/root/smartbot/src/utils/media_sender.py", line 65, in send_by_path
    entity = RequestUploadIqProtocolEntity(self.MEDIA_TYPE, filePath=path)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/protocol_media/protocolentities/iq_requestupload.py", line 27, in __init__
    assert os.path.exists(filePath), "Either specified path does not exist, or yowsup doesn't have permission to read: %s" % filePath
AssertionError: Either specified path does not exist, or yowsup doesn't have permission to read: /root/smartbot/media/ed646a3334ca891fd3467db13137214014469318.jpeg

**Comment by lomunet** [comment]
The file  /root/smartbot/media/ed646a3334ca891fd3467db13137214014469318.jpeg exist? Are you sure that the user that is running the service is the root user? You can try to change the media storage path to /tmp and check if is a permissions problem...

**Comment by joaoricardo000** [comment]
@lomunet is right.  
If the path exists, double check that the bot is really started by a root, or (better) change the media storage path and run with a non root user.

**Comment by x23piracy** [comment]
Hi,

i have the same issue and i don't think that this is a filesystem problem its seems that it's another pakage used that will not work as root: http://pastebin.com/9WNJP9pU

You are not allowed to run this app with root permissions.
If running without sudo doesn't work, you can either fix your permission problems or change where npm stores global packages by putting ~/npm/bin in your PATH and running:
npm config set prefix ~/npm

I've done what the error message told me also i uninstalled all npm modules and reinstalled them via nvm without needed root but anyway the error persists.

Any ideas?


Regards X23

**Comment by e0xify** [comment]
issue is still open for me,. any ideas?
