### ISSUE TITLE
Text to Speech Not working

### ISSUE THREAD

**Issue by haxxorsid** [joaoricardo000/whatsapp-bot-seed#83]
```
python src/server.py
_server.py_	[INFO][2016-06-10 00:09:29,061] ##################################################
_server.py_	[INFO][2016-06-10 00:09:29,061] 	Server started. Phone number: 919004094663
_server.py_	[INFO][2016-06-10 00:09:29,061] ##################################################
_router.py_	[INFO][2016-06-10 00:09:35,573] (PVT)[917039887080@s.whatsapp.net]	/tts "Hello"
_media_sender.py_	[INFO][2016-06-10 00:09:36,906] [Upload progress]de8870e0a51013c257e3752f33feae93.wav => 917039887080@s.whatsapp.net, 50% 
_media_sender.py_	[INFO][2016-06-10 00:09:38,193] [Upload progress]de8870e0a51013c257e3752f33feae93.wav => 917039887080@s.whatsapp.net, 100% 
_optionalmodules.py_	[ERROR][2016-06-10 00:09:38,194] ffvideo import failed
_mediauploader.py_	[ERROR][2016-06-10 00:09:38,194] Error occured at transfer type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 138, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/root/Desktop/whatsapp-bot-seed-master/src/utils/media_sender.py", line 91, in <lambda>
    caption)
  File "/root/Desktop/whatsapp-bot-seed-master/src/utils/media_sender.py", line 105, in _do_send_file
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(file_path, url, self.MEDIA_TYPE, ip, to)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 134, in fromFilePath
    entity = DownloadableMediaMessageProtocolEntity.fromFilePath(path, url, DownloadableMediaMessageProtocolEntity.MEDIA_TYPE_VIDEO, ip, to, mimeType, preview)
AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
```
I get this message which doing any /tts  use.

**Comment by c0d3x27** [comment]
i have this same problem can some one please solve it??'
