### ISSUE TITLE
URL search not working

### ISSUE THREAD

**Issue by haxxorsid** [joaoricardo000/whatsapp-bot-seed#85]
```
python src/server.py
_server.py_	[INFO][2016-06-10 00:12:28,453] ##################################################
_server.py_	[INFO][2016-06-10 00:12:28,453] 	Server started. Phone number: 919004094663
_server.py_	[INFO][2016-06-10 00:12:28,453] ##################################################
_router.py_	[INFO][2016-06-10 00:12:43,295] (PVT)[917039887080@s.whatsapp.net]	http://www.github.com
/bin/sh: 1: pageres: not found
_media_sender.py_	[ERROR][2016-06-10 00:12:43,300] Either specified path does not exist, or yowsup doesn't have permission to read: /tmp/dca96f4d853793f508e0059264c573c914654977.png
Traceback (most recent call last):
  File "/root/Desktop/whatsapp-bot-seed-master/src/utils/media_sender.py", line 52, in send_by_url
    self.send_by_path(jid, file_path, caption)
  File "/root/Desktop/whatsapp-bot-seed-master/src/utils/media_sender.py", line 64, in send_by_path
    entity = RequestUploadIqProtocolEntity(self.MEDIA_TYPE, filePath=path)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/iq_requestupload.py", line 28, in __init__
    assert os.path.exists(filePath), "Either specified path does not exist, or yowsup doesn't have permission to read: %s" % filePath
AssertionError: Either specified path does not exist, or yowsup doesn't have permission to read: /tmp/dca96f4d853793f508e0059264c573c914654977.png

```

Whenever I send a url like: http://www.github.com it doesn't send me any screens.

**Comment by TheJens90** [comment]
what is the nodejs version?
