### ISSUE TITLE
Error when receive message

### ISSUE THREAD

**Issue by Dev-Aryan** [joaoricardo000/whatsapp-bot-seed#87]
Hello,
First i was having AssertionErr then i fixed it from this [link](https://github.com/joaoricardo000/whatsapp-bot-seed/issues/55) by the code:
`You have to go to /usr/lib/python2.7/ and open the file asyncore.py
In the file, find the line 199 and change def loop(timeout=30.0, use_poll=False, map=None, count=None): to def loop(timeout=30.0, use_poll=True, map=None , count=None):`

After doing this i am having an `Bad file `descriptor``

Err_Log
`  self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_     [INFO][2016-07-09 16:17:42,580] Restarting..
_server.py_     [INFO][2016-07-09 16:17:42,581] ##################################################
_server.py_     [INFO][2016-07-09 16:17:42,581]         Server started. Phone number: ***********
_server.py_     [INFO][2016-07-09 16:17:42,581] ##################################################
_server.py_     [ERROR][2016-07-09 16:17:42,581] Unexpected Exception: 
Traceback (most recent call last):
  File "src/server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_     [INFO][2016-07-09 16:17:42,582] Restarting..
_server.py_     [INFO][2016-07-09 16:17:42,582] ####################################`

**Comment by montemarcaldera** [comment]
The fix that you quoted is for Bad file descriptor

**Comment by Dev-Aryan** [comment]
So, what should i do ?

**Comment by montemarcaldera** [comment]
Are you sure that you modified /usr/lib/python2.7/asyncore.py?

**Comment by Dev-Aryan** [comment]
yea i did

**Comment by ghost** [comment]
What to do ?
