### ISSUE TITLE
/i iPhone doesn't work

### ISSUE THREAD

**Issue by montemarcaldera** [joaoricardo000/whatsapp-bot-seed#9]
When I try to use /i iPhone, this happens:

_server.py_     [ERROR][2015-11-08 11:55:13,712] Unexpected Exception:
Traceback (most recent call last):
  File "smartbot/src/server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/lib/python2.7/site-packages/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_     [INFO][2015-11-08 11:55:13,712] Restarting..
##################################################
_server.py_     [INFO][2015-11-08 11:55:13,711]         Server started. Phone number: 1631XXXXXXX
_server.py_     [INFO][2015-11-08 11:55:13,711] ##################################################

**Comment by joaoricardo000** [comment]
https://github.com/joaoricardo000/whatsapp-bot-seed/issues/12
